### ISSUE TITLE
saurita permissions update

### ISSUE THREAD

**Issue by Alejandro9kgm** [JAM-Productions/saurita#13]
To add this update, I need the bot to receive a permissions update from the [Discord Developer Portal](https://discord.com/developers/docs/intro).

Step 1- Open the Discord Developer Portal.
Step 2- Go to Bot Settings
Step3- Enable the Required Intents(Privileged Gateway Intents)
             The intents are: Presence Intent, Server Members Intent, Message Content Intent

Step4- Save the changes

I need these permissions changes for my update to work properly, I would do it myself but I don't have the access to do it.

_Originally posted by @Alejandro9kgm in https://github.com/JAM-Productions/saurita/issues/3#issuecomment-2154325568_

**Comment by jorbush** [comment]
Done!
