### ISSUE TITLE
React to some text messages

### ISSUE THREAD

**Issue by jorbush** [JAM-Productions/saurita#3]
Follow [this section](https://discordjs.guide/popular-topics/reactions.html#reacting-to-messages) for add reactions for some messages.

For example, when someone ask something (when a message finish with "?"), it reacts with a "🧐".

**Comment by Alejandro9kgm** [comment]
To add this update, I need the bot to receive a permissions update from the [Discord Developer Portal](https://discord.com/developers/docs/intro).

Step 1- Open the Discord Developer Portal.
Step 2- Go to Bot Settings
Step3- Enable the Required Intents(Privileged Gateway Intents)
             The intents are: Presence Intent, Server Members Intent, Message Content Intent

Step4- Save the changes

I need these permissions changes for my update to work properly, I would do it myself but I don't have the access to do it.
